wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1702927529.246795
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.5
      5: 0.15.12
      6: 4.35.2
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
